# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kropsmaps' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kropsmaps
    pod 'GooglePlacePicker', '= 2.0.1'
    pod 'GooglePlaces', '= 2.0.1'
    pod 'GoogleMaps', '= 2.0.1'
    pod 'Firebase/Core'


  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end



